Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('kegiatan.urls')),
    path('', include('story9.urls')),

]

kegiatan/urls.py
from django.urls import path
from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('Activities/', views.activity, name='activities'),
    path('Activities/peserta/', views.peserta, name='peserta'),
    path('Activities/new/', views.new_activity, name='new_activity'),
    path('Activities/delete/<str:Nama_Kegiatan>', views.delete, name='delete'),

]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('About/', views.profile, name='About'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('class/', views.add_class, name='add_class'),
    path('class/new/', views.new_class, name='new_class'),
    path('class/delete/<str:mata_kuliah>', views.delete, name='delete')

]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('register/', views.register, name='register'),
    

]

kegiatan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Kegiatan(models.Model):
    Nama_Kegiatan = models.CharField(max_length = 50)

class Profile(models.Model):
    Kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    Nama = models.CharField(max_length = 50)


    
    

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class addmatkul(models.Model):
    mata_kuliah = models.CharField(max_length=50)
    dosen_pengajar = models.CharField (max_length=30)
    jumlah_sks = models.IntegerField ()
    deskripsi_mata_kuliah = models.TextField(max_length=600)
    semester_tahun = models.CharField(max_length=30)
    ruang_kelas = models.CharField (max_length=20)
    

story9/models.py
from django.db import models

# Create your models here.

kegiatan/forms.py
from django import forms
from .models import Profile, Kegiatan

class formKegiatan(forms.ModelForm):
	class Meta:
		model = Kegiatan
		fields = ['Nama_Kegiatan']
        
attrs = {'type' : 'text'}

error_messages = {
	'required' : 'Please Type'
}

	

Nama_Kegiatan = forms.CharField(label='Nama Kegiatan', required=False, max_length=50, widget=forms.TextInput(attrs=attrs),  error_messages={
               'required': 'Please enter activity name' })


class formProfile(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['Nama', 'Kegiatan']
        
attrs = {'type' : 'text'}

error_messages = {
	'required' : 'Please Type'
}

	

Nama = forms.CharField(label='Nama', required=False, max_length=50, widget=forms.TextInput(attrs=attrs),  error_messages={
               'required': 'Please enter your name' })
Kegiatan = forms.CharField(label='Nama', required=False, max_length=50, widget=forms.TextInput(attrs=attrs),  error_messages={
               'required': 'Please enter your name' })
 

main/forms.py
from django import forms
from .models import addmatkul

class MataKuliahform(forms.ModelForm):
	class Meta:
		model = addmatkul
		fields = ['mata_kuliah', 'dosen_pengajar', 'jumlah_sks', 'deskripsi_mata_kuliah', 'semester_tahun', 'ruang_kelas']
        
attrs = {'type' : 'text'}

error_messages = {
	'required' : 'Please Type'
}

	

mata_kuliah = forms.CharField(label='Nama mata kuliah', required=False, max_length=50, widget=forms.TextInput(attrs=attrs),  error_messages={
               'required': 'Please enter your name' })
dosen_pengajar = forms.CharField(label='Nama dosen', required=False, max_length=30, widget=forms.TextInput(attrs=attrs))
jumlah_sks = forms.CharField(label='Jumlah sks', required=False, widget=forms.TextInput(attrs=attrs))
deskripsi_mata_kuliah = forms.CharField(label='Deskripsi mata kuliah', required=False, max_length=600, widget=forms.Textarea(attrs=attrs))
semester_tahun= forms.CharField(label='Tahun ajaran', required=False, max_length=30, widget=forms.TextInput(attrs=attrs))
ruang_kelas = forms.CharField(label='Ruang kelas', required=False, max_length=20, widget=forms.TextInput(attrs=attrs))
 

kegiatan/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import formKegiatan, formProfile
from .models import Kegiatan


def activity(request):
    products = Kegiatan.objects.all
    return render(request, 'kegiatan/kegiatan.html', {'products':products})

def new_activity(request):
    if request.method == "POST":
        form = formKegiatan(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/Activities')
            
    else:
        form = formKegiatan()
    return render(request, 'kegiatan/formkegiatan.html', {'form': formKegiatan})

def peserta (request):
    if request.method == "POST":
        form = formProfile(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/Activities')
            
    else:
        form = formKegiatan()
    return render(request, 'kegiatan/peserta.html', {'form': formProfile})

def delete (request, Nama_Kegiatan):
    Kegiatan.objects.filter(Nama_Kegiatan= Nama_Kegiatan).delete()
    return redirect('/Activities')

# Create your views here.

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import MataKuliahform
from .models import addmatkul

def home(request):
    return render(request, 'main/home.html')

def profile(request):
    return render(request, 'main/Profile.html')

def portfolio (request):
    return render (request, 'main/Portfolio.html')

def add_class (request):
    products = addmatkul.objects.all
    return render (request, 'main/matakuliah.html', {'products':products})

def new_class (request):
   
    if request.method == "POST":
        form = MataKuliahform(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/class')
            
    else:
        form = MataKuliahform()
    return render(request, 'main/formmatkul.html', {'form': MataKuliahform})

def delete (request, mata_kuliah):
    addmatkul.objects.filter(mata_kuliah= mata_kuliah).delete()
    return redirect('/class')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
            
    else:
        form = AuthenticationForm()
    return render(request, "Story9/login.html", {'form': form})


def signout(request):
    logout(request)
    return redirect('/')

def register(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, "Story9/registration.html", {'form': form})

kegiatan/templates/kegiatan/kegiatan.html
{% extends 'base.html' %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock script %}

{% block content %}
<div class="container-fluid" id= "hasil-form">
    <div class="row">
        <div class="col-md-12">
           <h1 id="judul-hasilform">My Activities</h1> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12">
                <table id="table-matkul">
                    <tr>
                        <th class="row-tableform">Nama Kegiatan</th>
                        <th class="row-tableform">Peserta</th>
                        <th class="row-tableform">Aksi</th>
                     
                      </tr>
                    {% for i in products%}
                    <tr>
                        <td class="row-tableform"> 
                            {{ i.Nama_Kegiatan}} 
                        </td>
                        <td class="row-tableform">
                            {{ i.Nama}}
                        </td>
                        <td class="row-tableform">
                            <a style="font-size: large;" class="btn btn-primary" href="{% url 'kegiatan:peserta' %}">Tambah Peserta</a>
                            <a style="font-size: large;" class="btn btn-primary" href="delete/{{i.Nama_Kegiatan}}" onclick="return confirm ('Anda yakin ingin menghapus kegiatan ini?');" >Hapus</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr><td colspan="7" class="row-tableform">Currently there's no subject</td></tr>
                    {% endfor %}
                </table>  
                <br><br><br> 
                <a style="font-size: large;" class="btn btn-primary" href="{% url 'kegiatan:new_activity' %}" role="button">Add Activity</a>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Shabiqa's Page</title>
{% endblock meta %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 


{% endblock script %}

{% block content %}
 <!-- Jumbotron -->
 <div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
      <h1 class="display-4">Shabiqa Amani</h1>
      <hr class="hr2">
      <p class="lead ">passionate learner</p>
    </div>
  </div>
  <!-- Akhir Jumbotron-->

<!-- Personal Highlights & Contact-->

  <div class="container-fluid" id="personalhighlights">
      <div class="row">
          <div class="col-sm-12" >
              <h1 id="judul-PH">Personal Highlights</h1>
          </div>
      </div>

      <div class="row">
          <div class="col-sm-5 col-sm-offset-1">
              <img src="{% static "img/picture1.png" %}" class="foto1">
          </div>
          <div class="col-sm-6 " id="highlights">
              <p>Undergraduate Information System Student University of Indonesia</p>
              <br>
              <p>Participant of English Debate Competition</p>
              <br>
              <p>Born in Cirebon, 2nd of August 2001</p>
              <br>
              <p> TOEFL Score of 560</p>
              <br>
              <a style="font-size: medium;" class="btn btn-outline-primary" href="#more" role="button">CLICK ME</a>
          </div>
      </div>

      <div class="row">
        <div class="col-md" id="icon">
          <a href="mailto:shabiqaamani@gmail.com"><img class="foto" src="{% static "img/mail1.png" %}"></a>  
          <a href="https://www.linkedin.com/in/shabiqa-amani-42b807158/"><img class="foto" src="{% static "img/linkedin1.png" %}" id="icon1"></a>
          <a href="https://twitter.com/_shabiqaamani" ><img class="foto"  src="{% static "img/twitter1.png" %}" id="icon2"></a> 
          <a href= "https://www.instagram.com/shabiqaamani/"><img class="foto" src="{% static "img/instagram1.png" %}" id="icon3"></a>
        </div>
       
      </div>
  </div>
 

<!-- Experiences & Education -->

<div class="container-fluid" id="experience">
  <div class="row">
    <div class="col text-center" >
      <h1 id="judul">P.O.R.T.F.O.L.I.O</h1>
      <a style="font-size: medium;" class="btn btn-primary" href="{% url 'main:portfolio' %}" role="button">CLICK ME</a>
    </div>
   
  </div>
</div>

<!-- Skills -->

<div class="container-fluid" id="Skills">
    <div class="row">
      <div class="col-md" id="skill">
        <p> Java (Score: 3/5)</p>
        <p> Python (Score: 3/5)</p>
        <p> Data Science (Score: 3/5)</p>
        <p> Microsoft Word (Score: 4/5)</p>
        <p> Korean Language (Score: 3/5) </p>
        <p> English Language (Score: 4/5) </p>
        <p> Microsoft PowerPoint (Score: 4/5)</p>
      </div>

      <div class="col-md ">
        <h1 id="judul-skill">S.K.I.L.L.S</h1>
      </div>
    </div>
</div>

<!--This is My Life-->
<div class="container-fluid" id = "more">
  <div class="row">
    <div class="col-md-12 " >
      <h1 id="judul-TIML">This Is My Life...</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <img class="mylife" src="{% static "img/Picture2.png" %}" >
    </div>
    <div class="col-md-3">
      <img class="mylife-1" src="{% static "img/family.png" %}" >
    </div>
      <div class="col-md-3">
        <img class="mylife" src="{% static "img/teman.png" %}">
      </div>
      <div class="col-md-3">
        <img class="mylife-1" src="{% static "img/ariana.png" %}">
      </div>
  </div>
</div>


<div class="container-fluid">
  <div id="accordion">
    <h3>My Activity</h3>
    <div>
      <p>
        Staff of Keilmuan Department BEM Fasilkom UI
      </p>
    </div>
    <h3>Section 2</h3>
    <div>
      <p>
      Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
      purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
      velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
      suscipit faucibus urna.
      </p>
    </div>
    <h3>Section 3</h3>
    <div>
      <p>
      Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
      Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
      ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
      lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
      </p>
      <ul>
        <li>List item one</li>
        <li>List item two</li>
        <li>List item three</li>
      </ul>
    </div>
    <h3>Section 4</h3>
    <div>
      <p>
      Cras dictum. Pellentesque habitant morbi tristique senectus et netus
      et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
      faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
      mauris vel est.
      </p>
      <p>
      Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
      inceptos himenaeos.
      </p>
    </div>
  </div>
</div>



<script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

main/templates/main/matakuliah.html
{% extends 'base.html' %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock script %}

{% block content %}
<div class="container-fluid" id= "hasil-form">
    <div class="row">
        <div class="col-md-12">
           <h1 id="judul-hasilform">This Semester's Classes</h1> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12">
                <table id="table-matkul">
                    <tr>
                        <th class="row-tableform">Mata Kuliah</th>
                        <th class="row-tableform">Dosen Pengajar</th>
                        <th class="row-tableform" >Jumlah SKS</th>
                        <th class="row-tableform">Deskripsi</th>
                        <th class="row-tableform">Tahun Ajaran</th>
                        <th class="row-tableform">Ruang Kelas</th>
                        <th class="row-tableform">Aksi</th>
                      </tr>
                    {% for i in products%}
                    <tr>
                        <td class="row-tableform"> 
                            {{ i.mata_kuliah}} 
                        </td>
                        <td class="row-tableform">
                            {{ i.dosen_pengajar}}
                        </td>
                        <td class="row-tableform">
                            {{i.jumlah_sks}}
                        </td>
                        <td class="row-tableform">
                            {{i.deskripsi_mata_kuliah}}
                        </td>
                        <td class="row-tableform">
                            {{i.semester_tahun}}
                        </td>
                        <td class="row-tableform">
                            {{i.ruang_kelas}}
                        </td>
                        <td class="row-tableform">
                            <a class="btn btn-primary" href="delete/{{i.mata_kuliah}}" onclick="return confirm ('Anda yakin ingin menghapus mata kuliah ini?');" >Hapus</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr><td colspan="7" class="row-tableform">Currently there's no subject</td></tr>
                    {% endfor %}
                </table>  
                <br><br><br> 
                <a style="font-size: medium;" class="btn btn-primary" href="{% url 'main:new_class' %}" role="button">Add Class</a>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

story9/templates/Story9/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta%} <title>Login Form</title>{% endblock meta%}
{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock script %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="container-fluid" style="background-color: #2cacd7;">
 
  <div class="main">
      <h1 class="display-4" style="margin-top:5vw; color: #ffffff;">Log In</h1>   
  </div>
  <div class="login-page">
    
    <div class="login-form" >
      <form action="{% url 'story9:login' %}" method="POST">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {{ form|crispy }}
        <input type="submit" value="Login" style="color:white ; background-color: #2cacd7; margin-top: 3vw; font-size: large;">
      </form>
      <p style="margin-top: 2vw; font-size: medium;"> wanna try logging in? input <span>"admin"</span> as the username and the password</p>
      <p style="font-size: medium;"> Don't have an account? register <a href="{% url 'story9:register' %}">here</a> </p>
    </div>
    
  </div>
  
    
</div>

{% endblock content %}

story9/templates/Story9/registration.html
{% extends 'base.html' %}
{% load static %}

{% block meta%} <title>Registration Form</title>{% endblock meta%}

{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock script %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="container-fluid" style="background-color: #2cacd7; min-height: 700px;">

  {% if user.is_authenticated %}
  <div class="main">
    <h3 class="title3" style="margin-top:100px; font-size: 7vw; color: #ffffff; text-align: center;">You're <span>Logged</span> In </h3>
    <div class="center" style="text-align: center; margin:3vw">
      <p style="color: #ffffff; font-size: large;"> do you want to logout? </p>
      <a href="{% url 'story9:logout' %}">
              <button style="font-size: large;" class="btn btn-primary active" id="logout">Logout</button>
      </a>
  </div>

  </div>
  
  {% else %}
  <div class="main">
    <h1 class="display-4" style="margin-top:5vw; color: #ffffff;">Sign Up</h1> 
  </div>
  <div class="login-page">
    
    <div class="login-form" >
      <form action="{% url 'story9:register' %}" method="POST">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {{ form|crispy }}
        <input type="submit" value="Signup" style="color:white ; background-color: #2cacd7; margin-top: 1vw; font-size: large;">
      </form>
      <p style="margin-top: 1vw; font-size: medium;"> If you already have an account login <a href="{% url 'story9:login' %}">here</a> </p>
    </div>
    
  </div>
  {% endif %}
    
</div>

{% endblock content %}

templates/navbar.html
{% if user.is_authenticated %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light " id="navbar">
    <a class="navbar-brand " href="{% url 'main:home' %}">S.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        
          <ul class="nav navbar-nav ml-auto">
          <li><a class="nav-link " href="{% url 'main:About' %}">About<span class="sr-only">(current)</span></a></li>
          <li><a class="nav-link " href="/#personalhighlights">Highlights</a></li>
          <li><a class="nav-link " href="/#experience">Portfolio</a></li>
          <li><a class="nav-link " href="/#Skills">Skills</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Add
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a style="font-size: large;" class="dropdown-item" href="{% url 'main:add_class'%}"> Class </a>
              <a style="font-size: large;" class="dropdown-item" href="{% url 'kegiatan:activities' %}"> Activities</a>
            </div>
          </li>
          <li><a class="nav-link " href="{% url 'story9:register' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Hello, <span>{{ user }}</span></a></li>
          <li><a class="nav-link " href="{% url 'story9:logout' %}">Logout</a></li>
          </ul>
      </div>
    </nav>

{% else %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light " id="navbar">
  <a class="navbar-brand " href="{% url 'main:home' %}">S.</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      
        <ul class="nav navbar-nav ml-auto">
        <li><a class="nav-link " href="{% url 'main:About' %}">About<span class="sr-only">(current)</span></a></li>
        <li><a class="nav-link " href="/#personalhighlights">Highlights</a></li>
        <li><a class="nav-link " href="/#experience">Portfolio</a></li>
        <li><a class="nav-link " href="/#Skills">Skills</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a style="font-size: large;" class="dropdown-item" href="{% url 'main:add_class'%}"> Class </a>
            <a style="font-size: large;" class="dropdown-item" href="{% url 'kegiatan:activities' %}"> Activities</a>
          </div>
        </li>
        <li><a class="nav-link " href="{% url 'story9:register' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Register</a></li>
        <li><a class="nav-link " href="{% url 'story9:login' %}">Login</a></li>
        </ul>
    </div>
  </nav>
{% endif %}